- fqdn: joshtest.pulumi-workshops.com
  nsRecords:
    - ns-1160.awsdns-17.org
    - ns-1558.awsdns-02.co.uk
    - ns-490.awsdns-61.com
    - ns-971.awsdns-57.net
- fqdn: andy.pulumi-workshops.com
    - ns-1696.awsdns-20.co.uk.
    - ns-1173.awsdns-18.org.
    - ns-463.awsdns-57.com.
    - ns-615.awsdns-12.net.
